<Project>
  <PropertyGroup>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DisableXbfLineInfo>true</DisableXbfLineInfo>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <EnableXBindDiagnostics>false</EnableXBindDiagnostics>
    <PRIResourceMerging>false</PRIResourceMerging>
  </PropertyGroup>
</Project>
